name: Obfuscate and Commit

on:
  workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install -g javascript-obfuscator

      - name: List files to confirm worker.js exists
        run: ls -al

      - name: Obfuscate code (simplified for debugging)
        run: javascript-obfuscator worker.js --output _worker.js || echo "Obfuscation failed"

      - name: Check git status
        run: git status

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _worker.js || echo "No files to add"
          git commit -m "Obfuscate _worker.js" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
